name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start workflow
        run: echo "Starting workflow..."
      - name: Complete workflow
        run: echo "Completed workflow!"
